# Generated by Django 4.2.11 on 2024-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
